[package]
name = "alux-traversable"
description = "Traversable operations over Option and iterators, sequencing a short-circuiting effect"
documentation = "https://docs.rs/alux-traversable"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"

[dependencies]
extend.workspace = true

[lints]
workspace = true
